#!/bin/sh /etc/rc.common

START=15
STOP=10

boot() {
    auen
    # set default volume and enable
	if [ ! -f "/data/status/asound.state" ];then
    	alsactl -f /etc/asound.state restore
	else
    	alsactl -f /data/status/asound.state restore
	fi
}

stop() {
    alsactl -f /data/status/asound.state store
}
