#!/bin/sh /etc/rc.common
START=13

USE_PROCD=1

warn_log()
{
    echo "check_mac $*"
    logger -t check_mac -p 3 "$*"
}

start_service() {
	LAST_CONFIG_FILE=/tmp/mibt_config.json-old

	if [ ! -d /data/wifi ]; then
		echo Create /data/wifi folder ...
		/bin/mkdir /data/wifi
		/bin/chmod 777 /data/wifi
	fi
	if [ ! -d /data/bt ]; then
		echo Create /data/bt folder ...
		/bin/mkdir /data/bt
		/bin/chmod 777 /data/bt
	fi
	if [ ! -f /data/wifi/nvram.txt ]; then
		cp /etc/wifi/nvram.txt /data/wifi
		cp /etc/wifi/config.txt /data/wifi
	fi
	if [ ! -f /data/bt/bt_config.xml ]; then
		cp /etc/bt/bt_config.xml /data/bt
	fi
	if [ ! -f /data/bt/mibt_config.json ]; then
		cp /etc/bt/mibt_config.json /data/bt
	else
		mv /data/bt/mibt_config.json $LAST_CONFIG_FILE
		cp /etc/bt/mibt_config.json /data/bt
	fi
	if ! grep -Fq macaddr /data/wifi/nvram.txt
	then
		cp /etc/wifi/nvram.txt /data/wifi/nvram.txt
		cp /etc/wifi/config.txt /data/wifi/config.txt
	fi
	if ! grep -Fq bd_addr /data/bt/bt_config.xml
	then
		cp /etc/bt/bt_config.xml /data/bt/bt_config.xml
	fi

	KEYPATH=/sys/class/unifykeys
	echo "mac_wifi" > $KEYPATH/name
	mac_wifi=`cat $KEYPATH/read`
	str=`cat /data/wifi/nvram.txt |grep macaddr`
	old=`echo ${str#*=}`
	if [ "$mac_wifi" != "$old" ]; then
		/bin/config_update.sh /data/wifi/nvram.txt macaddr=$mac_wifi
	else
		echo NOT need modify WiFi MAC.
	fi

	echo "mac_bt" > $KEYPATH/name
	mac_bt=`cat $KEYPATH/read`
	str1=`cat /data/bt/bt_config.xml |grep bd_addr`
	str2=`echo ${str1#*>}`
	oldmac=`echo ${str2%:*}`
	if [ "$mac_bt" != "$oldmac" ]; then
		sed -i "s|<bd_addr>.*|<bd_addr>$mac_bt:</bd_addr>|" /data/bt/bt_config.xml
	else
		echo NOT need modify BT MAC.
	fi

CONFIGNAMETMP="mibt_config.json.tmp"
SOUNDBOXNAME="小米AI音箱"
BTCONFIGFILE="/data/bt/mibt_config.json"

oldmac=`cat $BTCONFIGFILE|grep bd_addr | awk -F "[\"\"]" '{print $4}'`
poststr=`echo ${mac_wifi} | awk -F "[\:]" '{print $5$6}'`
oldname=`cat $BTCONFIGFILE|grep bd_name | awk -F "[\"\"]" '{print $4}'`
sn=`getmac.sh sn`
discoverable=`cat $LAST_CONFIG_FILE | grep discoverable | awk -F "[\"]" '{print $4}'`
connectable=`cat $LAST_CONFIG_FILE | grep connectable | awk -F "[\"]" '{print $4}'`
sn_poststr=${sn:$((${#sn}-4))}
if [ "$sn_poststr" == "" ]; then
  sn_poststr="0001"
fi
if [ "${mac_bt}" != "$oldmac" -o "$oldname" != "${SOUNDBOXNAME}-${sn_poststr}"  ]; then
  cp -f $BTCONFIGFILE /tmp/${CONFIGNAMETMP}
  sed -i "s|bd_addr.*|bd_addr\": \"${mac_bt}\",|" /tmp/${CONFIGNAMETMP}
  sed -i "s|bd_name.*|bd_name\": \"${SOUNDBOXNAME}-${sn_poststr}\",|"  /tmp/${CONFIGNAMETMP}
  sed -i "s|discoverable.*|discoverable\": \"${discoverable}\",|"  /tmp/${CONFIGNAMETMP}
  sed -i "s|connectable.*|connectable\": \"${connectable}\",|"  /tmp/${CONFIGNAMETMP}
#修复部分配置出错的设备ｚ
  sed -i "s|bt_name.*|bd_name\": \"${SOUNDBOXNAME}-${sn_poststr}\",|"  /tmp/${CONFIGNAMETMP}
  cp -f /tmp/${CONFIGNAMETMP} $BTCONFIGFILE
  rm -rf $LAST_CONFIG_FILE
  echo "Modify BT MAC(JSON):${mac_bt}"
  echo "Modify BT NAME(JSON):${SOUNDBOXNAME}-${sn_poststr}"
  sync
else
  echo "NOT need modify BT MAC(JSON)."
fi

}
