#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2012 OpenWrt.org

START=62

USE_PROCD=1
PROG=/usr/sbin/dnsmasq

DNS_SERVERS=""
DOMAIN=""

ADD_LOCAL_DOMAIN=1
ADD_LOCAL_HOSTNAME=1

CONFIGFILE="/var/etc/dnsmasq.conf"
HOSTFILE="/tmp/hosts/dhcp"
TRUSTANCHORSFILE="/usr/share/dnsmasq/trust-anchors.conf"
TIMESTAMPFILE="/data/dnsmasq.time"

service_triggers()
{
	procd_add_reload_trigger "dhcp"
}

boot() {
	# Will be launched through hotplug
	return 0
}

start_service() {
	include /lib/functions

	config_load dhcp

	procd_open_instance
	procd_set_param command $PROG -C $CONFIGFILE -k -x /var/run/dnsmasq/dnsmasq.pid
	procd_set_param file $CONFIGFILE
	procd_set_param respawn

	procd_add_jail dnsmasq ubus log
	procd_add_jail_mount $CONFIGFILE $TRUSTANCHORSFILE $HOSTFILE /etc/passwd /etc/group /etc/TZ /dev/null /dev/urandom /etc/dnsmasq.conf /tmp/dnsmasq.d /tmp/resolv.conf.auto /etc/hosts /etc/ethers
	procd_add_jail_mount_rw /var/run/dnsmasq/ /tmp/dhcp.leases $TIMESTAMPFILE
	
	procd_close_instance

	# before we can call xappend
	mkdir -p /var/run/dnsmasq/
	mkdir -p $(dirname $CONFIGFILE)
	mkdir -p /var/lib/misc
	touch /tmp/dhcp.leases
    mkdir -p /tmp/hosts /tmp/dnsmasq.d

	if [ ! -f "$TIMESTAMPFILE" ]; then
		touch "$TIMESTAMPFILE"
		chown nobody.nogroup "$TIMESTAMPFILE"
	fi

	if [ -f /tmp/ap_config_mode_flag ]; then
		cp /etc/dnsmasq.conf.ap $CONFIGFILE
	else
		cp /etc/dnsmasq.conf.sta $CONFIGFILE
    fi
    
	rm -f /tmp/resolv.conf
	[ $ADD_LOCAL_DOMAIN -eq 1 ] && [ -n "$DOMAIN" ] && {
		echo "search $DOMAIN" >> /tmp/resolv.conf
	}
	DNS_SERVERS="$DNS_SERVERS 127.0.0.1"
	for DNS_SERVER in $DNS_SERVERS ; do
		echo "nameserver $DNS_SERVER" >> /tmp/resolv.conf
	done
}

reload_service() {
	rc_procd start_service "$@"
	return 0
}

stop_service() {
	[ -f /tmp/resolv.conf ] && {
		rm -f /tmp/resolv.conf
		ln -s /tmp/resolv.conf.auto /tmp/resolv.conf
	}
	rm -f /var/run/dnsmasq.*.dhcp
}
