#!/bin/sh /etc/rc.common

START=42

USE_PROCD=1
export LED_PARENT=led

nightmode_config_init()
{
    [ -f /data/etc/nightmode ] && return;
    mkdir -p /data/etc
    touch /data/etc/nightmode
    uci -c /data/etc/ set nightmode.mode=mode
    uci -c /data/etc/ set nightmode.mode.total=night
    uci -c /data/etc/ set nightmode.mode.light=night
    uci -c /data/etc/ set nightmode.mode.volume=night
    uci -c /data/etc/ set nightmode.mode.start=23:00
    uci -c /data/etc/ set nightmode.mode.stop=08:00
    uci -c /data/etc/ commit nightmode
    sync
}

start_service() {
    nightmode_config_init
    procd_open_instance
    procd_set_param command /bin/ledserver
    procd_set_param nice
    procd_append_param nice -10
    procd_set_param respawn 3600 5 0
    procd_close_instance
}

service_started() {
    /bin/show_led 4
}
