#!/bin/sh /etc/rc.common

START=70

USE_PROCD=1


start_service() {
  mkdir -p /data/notify
  procd_open_instance
  procd_set_param command /usr/bin/notifyd

  procd_set_param respawn 3600 5 0
  procd_close_instance
}

