#!/bin/sh /etc/rc.common

START=50
STOP=50
USE_PROCD=1
PROG=/bin/busybox
NAME=pass
PIDCOUNT=0

start_service() {
	procd_open_instance
	procd_set_param command $PROG passwd root -d
	procd_close_instance
}

shutdown() {
    stop
    #/usr/bin/killall dropbear
}
