#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1
DEBUG=0

start_service() {
    mkdir -p /tmp/mico-voip
    mkdir -p /data/voip/
    killall -9 voip_applite
    procd_open_instance
    procd_set_param command /usr/bin/voip_service
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_set_param respawn 3600 5 0
    procd_close_instance
}
